/*
THIS WORKSHEET IS FOR DEVELOPING THE STAGING LAYER FOR STORING RAW DATA 
FETCHED FROM Postgres DB.
AFTER THIS WE WILL DEVELOP FCT, DIM TABLES USING THIS STAGING LAYER DATA (USING DBT)
*/

-- USING SUPER USER
USE ROLE ACCOUNTADMIN;

-- CREATE DWH, DB, ROLE
CREATE WAREHOUSE IF NOT EXISTS AMAZON_MUSICAL_INSTRUMENTS_WH WITH WAREHOUSE_SIZE='x-small';
CREATE DATABASE IF NOT EXISTS MUSICAL_INSTRUMENTS_DB;
CREATE ROLE IF NOT EXISTS AMAZON_WH_ROLE;

-- Create User for Airbyte
CREATE USER IF NOT EXISTS AIRBYTE_USER
  PASSWORD = 'Snowflake@12345' 
  DEFAULT_ROLE = AMAZON_WH_ROLE
  DEFAULT_WAREHOUSE = AMAZON_MUSICAL_INSTRUMENTS_WH
  DEFAULT_NAMESPACE = MUSICAL_INSTRUMENTS_DB.MUSICAL_INSTRUMENTS_SCHEMA
  MUST_CHANGE_PASSWORD = FALSE;

SHOW GRANTS ON WAREHOUSE AMAZON_MUSICAL_INSTRUMENTS_WH;

-- GRANT USAGE ACCESS TO AMAZON_WH_ROLE ON WH
GRANT USAGE ON WAREHOUSE AMAZON_MUSICAL_INSTRUMENTS_WH TO AMAZON_WH_ROLE;

-- GRANT ROLE TO OUR USER 
GRANT ROLE AMAZON_WH_ROLE TO USER AIRBYTE_USER;

-- GRANT THE ROLE WE CREATED ALL ACCESS ON DB 
GRANT ALL ON DATABASE MUSICAL_INSTRUMENTS_DB TO ROLE AMAZON_WH_ROLE;


-- SWITCH TO WH_ROLE FROM ADMIN ROLE
USE ROLE AMAZON_WH_ROLE;

-- CREATE SCHEMA
CREATE SCHEMA MUSICAL_INSTRUMENTS_DB.MUSICAL_INSTRUMENTS_SCHEMA;

-- DATA CHECK AFTER LOAD
SELECT * FROM AIRBYTE_MUSICAL_INSTRUMENTS_REVIEWS;
-- YES WE HAVE :)

-- DROP DWH LATER
USE ROLE ACCOUNTADMIN;
DROP WAREHOUSE IF EXISTS AMAZON_MUSICAL_INSTRUMENTS_WH;
DROP DATABASE IF EXISTS MUSICAL_INSTRUMENTS_DB;
DROP ROLE IF EXISTS AMAZON_WH_ROLE;
